# This is a basic workflow to help you get started with Actions

name: Ansible Lint # feel free to pick your own name
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed for progressive mode to work

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        run: |
          sudo apt update
          sudo apt install -y ansible ansible-lint
          ansible-playbook -c local site.yml
