
# This is a basic workflow to help you get started with Actions
name: Playbook lint # feel free to pick your own name
on: push

jobs:
  Docker:
    runs-on: ubuntu-latest
    container:
      image: almalinux:latest
    steps:
      # Important: This sets up your GITHUB_WORKSPACE environment variable
      
      - uses: actions/checkout@v3
        #with:
        #  fetch-depth: 0 # needed for progressive mode to work
      - name: Run the playbooks on the server
        run: |
          dnf update
          dnf in -y epel-release
          dnf in -y ansible
          ansible-playbook --connection=local site.yml
  Vagrant:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Vagrant
        run: |
          sudo apt update
          sudo apt install -y virtualbox vagrant
          vagrant up --provision
  BareMetal:
    runs-on: ubuntu-latest
    steps:
      - name: Lint my playbook on GitHub's datacenters
        run: |
          sudo apt update
          sudo apt install -y ansible ansible-lint
          ansible-playbook -c local site.yml